```{r Necessary Packages}

library(tidyverse)
library(ggplot2)
install.packages("corrplot")
library(corrplot)

```

```{r Importing Data}

red_wines <- read.csv2("winequality-red.csv")
white_wines <- read.csv2("winequality-white.csv")

```

First Look at the Data:

```{r First Look}

head(red_wines)

head(white_wines)

```

Casting Data into Appropriate Types:

```{r Casting}

red_wines$quality <- as.numeric(red_wines$quality)
red_wines$fixed.acidity <- as.numeric(red_wines$fixed.acidity)
red_wines$volatile.acidity <- as.numeric(red_wines$volatile.acidity)
red_wines$citric.acid <- as.numeric(red_wines$citric.acid)
red_wines$residual.sugar <- as.numeric(red_wines$residual.sugar)
red_wines$chlorides <- as.numeric(red_wines$chlorides)
red_wines$free.sulfur.dioxide <- as.numeric(red_wines$free.sulfur.dioxide)
red_wines$total.sulfur.dioxide <- as.numeric(red_wines$total.sulfur.dioxide)
red_wines$density <- as.numeric(red_wines$density)
red_wines$pH <- as.numeric(red_wines$pH)
red_wines$sulphates <- as.numeric(red_wines$sulphates)
red_wines$alcohol <- as.numeric(red_wines$alcohol)

white_wines$quality <- as.numeric(white_wines$quality)
white_wines$fixed.acidity <- as.numeric(white_wines$fixed.acidity)
white_wines$volatile.acidity <- as.numeric(white_wines$volatile.acidity)
white_wines$citric.acid <- as.numeric(white_wines$citric.acid)
white_wines$residual.sugar <- as.numeric(white_wines$residual.sugar)
white_wines$chlorides <- as.numeric(white_wines$chlorides)
white_wines$free.sulfur.dioxide <- as.numeric(white_wines$free.sulfur.dioxide)
white_wines$total.sulfur.dioxide <- as.numeric(white_wines$total.sulfur.dioxide)
white_wines$density <- as.numeric(white_wines$density)
white_wines$pH <- as.numeric(white_wines$pH)
white_wines$sulphates <- as.numeric(white_wines$sulphates)
white_wines$alcohol <- as.numeric(white_wines$alcohol)

```

Second Look at Data:

```{r Data After Casting}

head(red_wines)

head(white_wines)

```


